#pragma once

#include <common/IDTO.h>

#include "gcs_core_export.h"

namespace gcs {

enum class ActionType : uint8_t {
    NEW_MISSION = 0,
    CLOSE_MISSION,

    UPDATE_CURRENT_MISSION_RESULT,
    UPDATE_MISSION_TASK,

    ADD_ROUTE,
    REMOVE_ROUTE,

    ADD_WAYPOINT,
    REMOVE_WAYPOINT,
    EDIT_WAYPOINT,
    CHANGE_SELECTED_WAYPOINT,

    UPDATE_LOADED_HOME,

    COPY_LOADED_ROUTE_TO_LOCAL,

    CHANGE_APPLICATION_STATUS,
    CHANGE_EDITION_MODE,
    CHANGE_VIEW_MODE,
    CHANGE_ROUTE_OPTIONS,

    SHOW_DIALOG,

    UPDATE_CURSOR_POSITION,
    UPDATE_MSG_CONSOLE,
    ADD_MEASURING_POINT,
    REMOVE_MEASURING_POINTS,

    UPDATE_CLOUD_DIMENSIONS,
    EDIT_POINTCLOUD,
    RESTORE_POINTCLOUD,
    HIDE_POINTCLOUD,
    HIDE_CUT_PLANE,
    HIDE_PREVIEW_AXIS,

    COMMS_CONNECT,
    COMMS_DISCONNECT,

    UPDATE_COMMS_STATUS,
    UPDATE_COMMS_PROGRESS,

    UPDATE_LOADED_ROUTE,
    UPDATE_LOADED_ROUTE_FROM_CURRENT_ROUTE,
    REMOVE_LOADED_ROUTE,
    REMOVE_LOADED_HOME,

    UPDATE_VISUALIZATION_CONFIG,

    SAVE_CURRENT_WPTS_LIST,
    SAVE_AS_CURRENT_WPTS_LIST,
    LOAD_ASSOCIATED_WPTS_LIST,

    MODIFY_CURR_WP_HEADING,
    MODIFY_PREVIEW_WP_HEADING,

    MANAGE_AUTOHEADING_WPTS,

    // DDHL actions
    UPDATE_COMMS_LINK_DDHL,
    DOWNLOAD_INSP_PLAN_FROM_DDHL,
    DOWNLOAD_SITE_LIST_FROM_DDHL,
    LOAD_INSPECTION_PLAN_FROM_LOCAL,
    LOAD_XML_DATA_FROM_FOLDER,
    LOAD_CURRENT_INSPECTION_PLAN,
    UPDATE_INSPECTION_PLAN,
    UPDATE_SITE_LIST,
    UPDATE_ASSET_PATH,
    UPDATE_ASSET_PROGRESS,
    CANCEL_ASSET_DOWNLOAD,
    LOAD_MISSION_RESULT_LIST_FROM_FOLDER,
    UPLOAD_MISSION_RESULT_LIST_TO_DDHL,
    REMOVE_MISSION_RESULT,
    DOWNLOAD_ASSET_FROM_DDHL,

    // PILOTING actions
    UPLOAD_WAYPOINTS_LIST,
    DOWNLOAD_WAYPOINTS_LIST,
    SET_CURRENT_WAYPOINT_ITEM,

    DOWNLOAD_ALARMS_LIST,
    RECEIVE_ALARMS_LIST,
    UPDATE_ALARM_STATUS,

    DOWNLOAD_HLACTION_LIST,
    RECEIVE_HLACTION_LIST,

    UPDATE_CURRENT_INSP_ITEM,
    UPDATE_REACHED_INSP_ITEM,

    DOWNLOAD_CHECKLIST,
    RECEIVE_CHECKLIST,
    UPDATE_CHECKLIST,

    SEND_HOME,

    SEND_COMMAND,
    UPDATE_POSITION_VELOCITY_NED,
    UPDATE_ATTITUDE_ANGVELOCITY,
    UPDATE_VIEW_INSPECTION_TASK,

    First = NEW_MISSION,
    Last  = UPDATE_VIEW_INSPECTION_TASK
};

class PILOTING_GRCS_CORE_EXPORT IAction
{
  public:
    virtual ~IAction() {}

    virtual ActionType getActionType() = 0;

    virtual void execute(QSharedPointer<IDTO>) = 0;

    /// Q_SIGNALS:
    virtual void sendDTO(QSharedPointer<IDTO>) = 0;
};

} // namespace gcs

Q_DECLARE_METATYPE(gcs::ActionType)
