SET(CPACK_PACKAGE_NAME                 ${PROJECT_NAME})
SET(CPACK_PACKAGE_VENDOR               "FADA-CATEC")
SET(CPACK_PACKAGE_CONTACT              "Marco A. Montes Grova <mmontes@catec.aero>")
SET(CPACK_PACKAGE_MAINTAINER           ${CPACK_PACKAGE_CONTACT})
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY  "PILOTING General Robot Control Station")

SET(CPACK_PACKAGE_VERSION              ${VERSION})
SET(CPACK_PACKAGE_VERSION_MAJOR        ${VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR        ${VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH        ${VERSION_PATCH})

IF(${UNIX})
   SET(CPACK_GENERATOR           "DEB")
   SET(CPACK_SET_DESTDIR         ON)

   SET(CPACK_PACKAGE_FILE_NAME   "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}_${CMAKE_SYSTEM_PROCESSOR}")

   SET(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
      "${PROJECT_BINARY_DIR}/postinst"
      "${PROJECT_BINARY_DIR}/postrm")
ENDIF()

INCLUDE(CPack)
